package com.pe.appweb.proybiblioteca.entidades;
// Generated 25/11/2017 05:12:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private int idAutor;
     private String nombre;
     private String apellido;
     private String nacionalidad;
     private String sexo;
     private Set libroporautors = new HashSet(0);

    public Autor() {
    }

	
    public Autor(int idAutor, String nombre, String apellido, String nacionalidad) {
        this.idAutor = idAutor;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nacionalidad = nacionalidad;
    }
    public Autor(int idAutor, String nombre, String apellido, String nacionalidad, String sexo, Set libroporautors) {
       this.idAutor = idAutor;
       this.nombre = nombre;
       this.apellido = apellido;
       this.nacionalidad = nacionalidad;
       this.sexo = sexo;
       this.libroporautors = libroporautors;
    }
   
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Set getLibroporautors() {
        return this.libroporautors;
    }
    
    public void setLibroporautors(Set libroporautors) {
        this.libroporautors = libroporautors;
    }




}


