package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Copia generated by hbm2java
 */
public class Copia  implements java.io.Serializable {

    private int idCopia;
    private int estado;
    private int idLibro;
    private int edicion;
    private String editorial;
    
    public Copia() {
    }

    public Copia(int idCopia, int estado, int idLibro, int edicion, String editorial) {
        this.idCopia = idCopia;
        this.estado = estado;
        this.idLibro = idLibro;
        this.edicion = edicion;
        this.editorial = editorial;
    }

    public int getIdCopia() {
        return idCopia;
    }

    public void setIdCopia(int idCopia) {
        this.idCopia = idCopia;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public int getIdLibro() {
        return idLibro;
    }

    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }

    public int getEdicion() {
        return edicion;
    }

    public void setEdicion(int edicion) {
        this.edicion = edicion;
    }

    public String getEditorial() {
        return editorial;
    }

    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }


}


