package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Copia generated by hbm2java
 */
public class Copia  implements java.io.Serializable {


     private String idCopia;
     private Libro libro;
     private boolean estado;
     private Set prestamos = new HashSet(0);

    public Copia() {
    }

	
    public Copia(String idCopia, Libro libro, boolean estado) {
        this.idCopia = idCopia;
        this.libro = libro;
        this.estado = estado;
    }
    public Copia(String idCopia, Libro libro, boolean estado, Set prestamos) {
       this.idCopia = idCopia;
       this.libro = libro;
       this.estado = estado;
       this.prestamos = prestamos;
    }
   
    public String getIdCopia() {
        return this.idCopia;
    }
    
    public void setIdCopia(String idCopia) {
        this.idCopia = idCopia;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


