package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lector generated by hbm2java
 */
public class Lector  implements java.io.Serializable {
     private int codigo;
     private String nombres;
     private String apellidos;
     private int telefono;
     private String sexo;
     private int estado;
     private int strikes;

    public Lector() {
    }

    public Lector(int codigo, String nombres, String apellidos, int telefono, String sexo, int estado, int strikes, Set prestamos, Set multas) {
       this.codigo = codigo;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.sexo = sexo;
       this.estado = estado;
       this.strikes = strikes;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int setEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public int getStrikes() {
        return this.strikes;
    }
    
    public void setStrikes(int strikes) {
        this.strikes = strikes;
    }

    public int getEstado() {
        return estado;
    }
}


