package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1



/**
 * Libroporautor generated by hbm2java
 */
public class Libroporautor  implements java.io.Serializable {


     private int idLibroPorAutor;
     private int idAutor;
     private int idLibro;

    public Libroporautor() {
    }

    public int getIdLibroPorAutor() {
        return idLibroPorAutor;
    }

    public void setIdLibroPorAutor(int idLibroPorAutor) {
        this.idLibroPorAutor = idLibroPorAutor;
    }

    public int getIdAutor() {
        return idAutor;
    }

    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }

    public int getIdLibro() {
        return idLibro;
    }

    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }
    
    




}


