package com.pe.appweb.proybiblioteca.entidades;
// Generated 25/11/2017 05:12:29 PM by Hibernate Tools 4.3.1



/**
 * Libroporautor generated by hbm2java
 */
public class Libroporautor  implements java.io.Serializable {


     private int idLibroPorAutor;
     private Autor autor;
     private Libro libro;

    public Libroporautor() {
    }

    public Libroporautor(int idLibroPorAutor, Autor autor, Libro libro) {
       this.idLibroPorAutor = idLibroPorAutor;
       this.autor = autor;
       this.libro = libro;
    }
   
    public int getIdLibroPorAutor() {
        return this.idLibroPorAutor;
    }
    
    public void setIdLibroPorAutor(int idLibroPorAutor) {
        this.idLibroPorAutor = idLibroPorAutor;
    }
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }




}


