package com.pe.appweb.proybiblioteca.entidades;
// Generated 25/11/2017 05:12:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private int idLibro;
     private Tipo tipo;
     private String titulo;
     private int edicion;
     private Set libroporautors = new HashSet(0);
     private Set copias = new HashSet(0);

    public Libro() {
    }

	
    public Libro(int idLibro, Tipo tipo, String titulo, int edicion) {
        this.idLibro = idLibro;
        this.tipo = tipo;
        this.titulo = titulo;
        this.edicion = edicion;
    }
    public Libro(int idLibro, Tipo tipo, String titulo, int edicion, Set libroporautors, Set copias) {
       this.idLibro = idLibro;
       this.tipo = tipo;
       this.titulo = titulo;
       this.edicion = edicion;
       this.libroporautors = libroporautors;
       this.copias = copias;
    }
   
    public int getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public int getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(int edicion) {
        this.edicion = edicion;
    }
    public Set getLibroporautors() {
        return this.libroporautors;
    }
    
    public void setLibroporautors(Set libroporautors) {
        this.libroporautors = libroporautors;
    }
    public Set getCopias() {
        return this.copias;
    }
    
    public void setCopias(Set copias) {
        this.copias = copias;
    }




}


