package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.sql.Date;

/**
 * Multa generated by hbm2java
 */
public class Multa  implements java.io.Serializable {

    private int idMulta;
    private Date inicio;
    private Date fin;
    private int monto;
    private String cadinicio;
    private String cadfin;

    public Multa() {
    }

    public Multa(int idMulta, Date inicio, Date fin, int monto) {
        this.idMulta = idMulta;
        this.inicio=(inicio);
        this.fin=(fin);
        this.cadinicio= String.valueOf(inicio.getDate())+"/" + String.valueOf(inicio.getMonth())+"/" +String.valueOf(inicio.getYear());
        this.cadfin= String.valueOf(fin.getDate()) +"/" +String.valueOf(fin.getMonth())+"/" +String.valueOf(fin.getYear());
        this.monto = monto;
    }

    public int getIdMulta() {
        return idMulta;
    }

    public void setIdMulta(int idMulta) {
        this.idMulta = idMulta;
    }

    public Date getInicio() {
        return inicio;
    }

    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }

    public Date getFin() {
        return fin;
    }

    public void setFin(Date fin) {
        this.fin = fin;
    }

    public int getMonto() {
        return monto;
    }

    public void setMonto(int monto) {
        this.monto = monto;
    }

    public String getCadinicio() {
        if(this.cadinicio==null){
            if(inicio!=null){
                return String.valueOf(inicio.getDate())+"/" + String.valueOf(inicio.getMonth())+"/" +String.valueOf(inicio.getYear());
            }else{
                return "";
            }
        }else{
            return cadinicio;
        }
    }

    public void setCadinicio(String cadinicio) {
        this.cadinicio = cadinicio;
    }

    public String getCadfin(){ 
        if(this.cadinicio==null){
            if(fin!=null){
                return String.valueOf(fin.getDate()) +"/" +String.valueOf(fin.getMonth())+"/" +String.valueOf(fin.getYear());
            }else{
                return "";
            }
        }else{
            return cadfin;
        }
    }

    public void setCadfin(String cadfin) {
        this.cadfin = cadfin;
    }

}


