package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Multa generated by hbm2java
 */
public class Multa  implements java.io.Serializable {

     private int idMulta;
     private Date inicio;
     private Date fin;
     private int monto;

    public Multa() {
    }

    public Multa(int idMulta, Date inicio, Date fin, int monto) {
        this.idMulta = idMulta;
        this.inicio = inicio;
        this.fin = fin;
        this.monto = monto;
    }

    public int getIdMulta() {
        return idMulta;
    }

    public void setIdMulta(int idMulta) {
        this.idMulta = idMulta;
    }

    public Date getInicio() {
        return inicio;
    }

    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }

    public Date getFin() {
        return fin;
    }

    public void setFin(Date fin) {
        this.fin = fin;
    }

    public int getMonto() {
        return monto;
    }

    public void setMonto(int monto) {
        this.monto = monto;
    }

    



}


