package com.pe.appweb.proybiblioteca.entidades;
// Generated 25/11/2017 05:12:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Multa generated by hbm2java
 */
public class Multa  implements java.io.Serializable {


     private int idMulta;
     private Lector lector;
     private Date inicio;
     private Date fin;
     private int monto;

    public Multa() {
    }

    public Multa(int idMulta, Lector lector, Date inicio, Date fin, int monto) {
       this.idMulta = idMulta;
       this.lector = lector;
       this.inicio = inicio;
       this.fin = fin;
       this.monto = monto;
    }
   
    public int getIdMulta() {
        return this.idMulta;
    }
    
    public void setIdMulta(int idMulta) {
        this.idMulta = idMulta;
    }
    public Lector getLector() {
        return this.lector;
    }
    
    public void setLector(Lector lector) {
        this.lector = lector;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }




}


