package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {
     private int idPersonal;
     private String nombre;
     private String apellido;
     private Integer telefono;
     private String correo;
     private String sexo;
     private int idTipopersonal;
     
    public Personal() {
    }

    public Personal(int idPersonal, int idTipopersonal, String nombre, String apellido, Integer telefono, String correo, String sexo) {
        this.idPersonal = idPersonal;
        this.idTipopersonal = idTipopersonal;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.correo = correo;
        this.sexo = sexo;
    }

    public int getIdPersonal() {
        return idPersonal;
    }

    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }

    public int getIdTipopersonal() {
        return idTipopersonal;
    }

    public void setIdTipopersonal(int idTipopersonal) {
        this.idTipopersonal = idTipopersonal;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public Integer getTelefono() {
        return telefono;
    }

    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }


}


