package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int idPersonal;
     private Tipopersonal tipopersonal;
     private String nombre;
     private String apellido;
     private Integer telefono;
     private String correo;
     private String sexo;
     private Set prestamos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int idPersonal, Tipopersonal tipopersonal, String nombre, String apellido, String sexo) {
        this.idPersonal = idPersonal;
        this.tipopersonal = tipopersonal;
        this.nombre = nombre;
        this.apellido = apellido;
        this.sexo = sexo;
    }
    public Personal(int idPersonal, Tipopersonal tipopersonal, String nombre, String apellido, Integer telefono, String correo, String sexo, Set prestamos, Set usuarios) {
       this.idPersonal = idPersonal;
       this.tipopersonal = tipopersonal;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.correo = correo;
       this.sexo = sexo;
       this.prestamos = prestamos;
       this.usuarios = usuarios;
    }
   
    public int getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }
    public Tipopersonal getTipopersonal() {
        return this.tipopersonal;
    }
    
    public void setTipopersonal(Tipopersonal tipopersonal) {
        this.tipopersonal = tipopersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


