package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private int idPrestamo;
     private Copia copia;
     private Lector lector;
     private Personal personal;
     private Date inicio;
     private Date fin;

    public Prestamo() {
    }

    public Prestamo(int idPrestamo, Copia copia, Lector lector, Personal personal, Date inicio, Date fin) {
       this.idPrestamo = idPrestamo;
       this.copia = copia;
       this.lector = lector;
       this.personal = personal;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public int getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Copia getCopia() {
        return this.copia;
    }
    
    public void setCopia(Copia copia) {
        this.copia = copia;
    }
    public Lector getLector() {
        return this.lector;
    }
    
    public void setLector(Lector lector) {
        this.lector = lector;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }




}


