package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1


import java.sql.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {

     private int idPrestamo;
     private Date inicio;
     private Date fin;
     private String cadinicio;
     private String cadfin;
     private int idLector;
     private int idPersonal;
     private int idCopia;
     private int devuelto;
     private int agregado;
     private int idMulta;
     
    public Prestamo() {
    }

    public Prestamo(int idPrestamo, Date inicio, Date fin, int idLector, int idPersonal, int idCopia, int devuelto, int agregado, int idMulta) {
        this.idPrestamo = idPrestamo;
        this.inicio = inicio;
        this.fin = fin;
        this.idLector = idLector;
        this.idPersonal = idPersonal;
        this.idCopia = idCopia;
        this.devuelto = devuelto;
        this.agregado = agregado;
        this.idMulta = idMulta;
    }

    public int getIdPrestamo() {
        return idPrestamo;
    }

    public void setIdPrestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }

    public Date getInicio() {
        return inicio;
    }

    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }

    public Date getFin() {
        return fin;
    }

    public void setFin(Date fin) {
        this.fin = fin;
    }

    public int getIdLector() {
        return idLector;
    }

    public void setIdLector(int idLector) {
        this.idLector = idLector;
    }

    public int getIdPersonal() {
        return idPersonal;
    }

    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }

    public int getIdCopia() {
        return idCopia;
    }

    public void setIdCopia(int idCopia) {
        this.idCopia = idCopia;
    }

    public int getDevuelto() {
        return devuelto;
    }

    public void setDevuelto(int devuelto) {
        this.devuelto = devuelto;
    }

    public int getAgregado() {
        return agregado;
    }

    public void setAgregado(int agregado) {
        this.agregado = agregado;
    }

    public int getIdMulta() {
        return idMulta;
    }

    public void setIdMulta(int idMulta) {
        this.idMulta = idMulta;
    }

    public String getCadinicio() {
        return cadinicio;
    }

    public void setCadinicio(String cadinicio) {
        this.cadinicio = cadinicio;
    }

    public String getCadfin() {
        return cadfin;
    }

    public void setCadfin(String cadfin) {
        this.cadfin = cadfin;
    }
    
    

}


