package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1

/**
 * Tipopersonal generated by hbm2java
 */
public class Tipopersonal  implements java.io.Serializable {


     private int idTipoPersonal;
     private String nombre;
     
    public Tipopersonal() {
    }

    public int getIdTipoPersonal() {
        return idTipoPersonal;
    }

    public void setIdTipoPersonal(int idTipoPersonal) {
        this.idTipoPersonal = idTipoPersonal;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}


