package com.pe.appweb.proybiblioteca.entidades;
// Generated 25/11/2017 05:12:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopersonal generated by hbm2java
 */
public class Tipopersonal  implements java.io.Serializable {


     private int idTipoPersonal;
     private String nombre;
     private Set personals = new HashSet(0);

    public Tipopersonal() {
    }

	
    public Tipopersonal(int idTipoPersonal, String nombre) {
        this.idTipoPersonal = idTipoPersonal;
        this.nombre = nombre;
    }
    public Tipopersonal(int idTipoPersonal, String nombre, Set personals) {
       this.idTipoPersonal = idTipoPersonal;
       this.nombre = nombre;
       this.personals = personals;
    }
   
    public int getIdTipoPersonal() {
        return this.idTipoPersonal;
    }
    
    public void setIdTipoPersonal(int idTipoPersonal) {
        this.idTipoPersonal = idTipoPersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }




}


