package com.pe.appweb.proybiblioteca.entidades;
// Generated 29/11/2017 02:28:28 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

     private int idUsuario;
     private int idPersonal;
     private String nombreusuario;
     private String claveusuario;

    public Usuario() {
    }

    public Usuario(int idUsuario, int idPersonal, String nombreusuario, String claveusuario) {
        this.idUsuario = idUsuario;
        this.idPersonal = idPersonal;
        this.nombreusuario = nombreusuario;
        this.claveusuario = claveusuario;
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public int getIdPersonal() {
        return idPersonal;
    }

    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }

    public String getNombreusuario() {
        return nombreusuario;
    }

    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }

    public String getClaveusuario() {
        return claveusuario;
    }

    public void setClaveusuario(String claveusuario) {
        this.claveusuario = claveusuario;
    }
    
}


